var sentences = [
    "The unrelenting orgasms from his [noun-penis] [verb-sex-present] my [noun-vagina] made me come so hard, I began sweating like [simile-sweat].",
    "After having my [noun-vagina] [verb-sex-past], he then proceeded to [verb-sex-root] my [noun-anus].",
    "The [verb-sex-present] makes me [verb-squirt-root] my [noun-lady_cum] all over his [noun-penis].",
    "By now, my [noun-vagina] was [verb-dribble-present] like [simile-dribble].",
    "I can't wait to [verb-suck-root] the [noun-semen] from his [noun-penis].",
    "My [noun-vagina] was trembling like [simile-shake].",
    "Inserting [noun-insertable] into my [noun-vagina] got me [verb-squirt-present] [noun-lady_cum] faster than [simile-fast].",
    "The [verb-sex-present] of my [noun-anus] was so vigorous, he soon found his [noun-testes] joining his [noun-penis] deep in my [noun-anus].",
    "He munched on my [noun-labia], even though I'd [noun-menstruation] for the best part of a week.",
    "He [verb-defecate-past] a giant [noun-faeces] on my [noun-breasts] just so he could [verb-suck-root] it up like [simile-eat].",
    "With his [noun-penis] [verb-sex-present] deep into my [noun-vagina], the sensation of his [noun-penis] smashing my cervix made me [verb-shake-root] like [simile-shake].",
    "When he removed his [noun-penis] from my [noun-anus], he was pleasantly surprised to see a [noun-faeces] staring back as him. He knew I couldn't wait to [verb-suck-root] the [noun-faeces] off his [noun-penis].",
    "Within no time, I could feel the shitty [noun-semen] [verb-dribble-present] from my [noun-anus] and all over my [noun-labia].",
    "Hours of [verb-sex-present] like this would leave any girl's [noun-labia] looking like [simile-sore], and I was no different!",
    "The mixture of [noun-faeces] and [noun-semen] in my [noun-anus] created the delicious [noun-seepage] that he was so fond of.",
    "Now, I've [simile-promiscuous], but the sight of his [noun-penis] made my [noun-lady_cum] [verb-dribble-root] like [simile-dribble].",
    "The seemingly never-ending streams of [noun-semen] emanating from his [noun-penis] soon had me coated like a plasterer's radio.",
    "I awoke the next morning with my [noun-vagina] still [verb-dribble-present]. I thought it was over but his [noun-penis] had other ideas.",
    "With my [noun-labia] now much like [simile-sore], he thought it was time to start [verb-insert-present] my [noun-anus]. Is now the time to tell him I really need to [verb-defecate-root] a [noun-faeces], I wondered?",
    "The feeling of his [noun-semen] [verb-dribble-present] down my throat got my [noun-lady_cum] flowing quicker than [simile-fast].",
    "It was bliss having his [noun-penis] [verb-insert-past] inside me again; stuffing my [noun-vagina] with [noun-insertable] just didn't get my [noun-vagina] [verb-squirt-present] like it used to.",
    "There was [noun-semen] [verb-dribble-present] from his [noun-penis] and I was wetter than [simile-wet]. We were ready for more.",
    "My [noun-mouth] was so full of [noun-penis] and [noun-semen], the [noun-semen] was [verb-dribble-present] down my chin and onto my [noun-breasts].",
    "Leaving my panties sunny side up on the floor was the least of my worries as his [noun-penis] [verb-insert-past] deeper into my [noun-anus].",
    "Some girls are happy just to [noun-masturbate] when they're alone, but I can't get off without having [noun-insertable] in my [noun-vagina] and [noun-insertable] up my [noun-anus].",
    "If I don't [noun-masturbate] to get my [noun-lady_cum] [verb-dribble-present] from my [noun-vagina], his [noun-penis] is going to leave my [noun-labia] resembling [simile-sore]."
];