var vocab = {
    "verbs" : {
        "sex" : [
            ["fuck", "fucked", "fucking"],
            ["hammer", "hammered", "hammering"],
            ["plow", "plowed", "plowing"],
            ["pound", "pounded", "pounding"],
            ["raid", "raided", "raiding"],
            ["slam", "slammed", "slamming"],
            ["thrust", "thrusted", "thrusting"]
        ],
        "insert" : [
            ["plunge", "plunged", "plunging"],
            ["probe", "probed", "probing"],
            ["ram", "rammed", "ramming"],
            ["shove", "shoved", "shoving"],
            ["slide", "slid", "sliding"],
            ["stuff", "stuffed", "stuffing"]
        ],
        "squirt" : [
            ["eject", "ejected", "ejecting"],
            ["flood", "flooded", "flooding"],
            ["flow", "flowed", "flowing"],
            ["gush", "gushed", "gushing"],
            ["pour", "poured", "pouring"],
            ["spit", "spattered", "spattering"],
            ["splurge", "splurged", "splurging"],
            ["spout", "spouted", "spouting"],
            ["spray", "sprayed", "spraying"],
            ["spritz", "spritzed", "spritzing"],
            ["squirt", "squirted", "squirting"],
            ["surge", "surged", "surging"]
        ],
        "dribble" : [
            ["drain", "drained", "draining"],
            ["dribble", "dribbled", "dribbling"],
            ["drip", "dripped", "dripping"],
            ["flow", "flowed", "flowing"],
            ["foam", "foamed", "foaming"],
            ["froth", "frothed", "frothing"],
            ["haemorrhage", "haemorrhaged", "haemorrhaging"],
            ["leach", "leached", "leaching"],
            ["leak", "leaked", "leaking"],
            ["ooze", "oozed", "oozing"],
            ["seep", "seeped", "seeping"],
            ["slime", "slimed", "sliming"],
            ["slobber", "slobbered", "slobbering"],
            ["trickle", "trickled", "trickling"],
            ["weep", "wept", "weeping"]
        ],
        "suck" : [
            ["chow down on", "chowed down on", "chowing down on"],
            ["consume", "consumed", "consuming"],
            ["devour", "devoured", "devouring"],
            ["gobble", "gobbled", "gobbling"],
            ["lap", "lapped", "lapping"],
            ["suck", "sucked", "sucking"]
        ],
        "defecate" : [
            ["arc", "arced", "arcing"],
            ["blast", "blasted", "blasting"],
            ["cop", "copped", "copping"],
            ["crown", "crowned", "crowning"],
            ["curl", "curled", "curling"],
            ["cut", "cut", "cutting"],
            ["drop", "dropped", "dropping"],
            ["ease", "eased out", "easing out"],
            ["extrude", "extruded", "extruding"],
            ["launch", "launched", "launching"],
            ["pinch off", "pinched off", "pinching off"],
            ["pitch", "pitched", "pitching"],
            ["roll", "rolled", "rolling"]
        ],
        "shake" : [
            ["quake", "quaked", "quaking"],
            ["quiver", "quivered", "quivering"]
        ]
    },
    "nouns" : {
        "anus" : [
            "balloon knot",
            "black hole",
            "brown eye",
            "brown mile",
            "cocoa channel",
            "chocolate starfish",
            "fart valve",
            "fudge factory",
            "marmite motorway",
            "Mavis Fritter",
            "mud flap",
            "old dirt road",
            "other vagina",
            "Oxo orifice",
            "poop chute",
            "poo pipe",
            "puckered brown eye",
            "ring piece",
            "rusty bullet hole",
            "rusty sherif's badge",
            "soft tight anus",
            "shit winker",
            "tradesman's entrance",
            "turd cutter",
            "turd-herder",
            "vintage golf bag"
        ],
        "breasts" : [
            "boobage",
            "breasticles",
            "cans",
            "chesticles",
            "chest puppies",
            "droopies",
            "fiery biscuits",
            "love bubbles",
            "mammaries",
            "mosquito bites",
            "rack",
            "superdroopers",
            "sweater puppies",
            "tatas",
            "top bollocks",
            "twin peaks"
        ],
        "faeces" : [
            "butt nugget",
            "colon cobra",
            "corn-eyed butt snake",
            "footlong fudge bullet",
            "hardened fudge nugget",
            "Mr. Hanky",
            "sewer trout",
            "stink pickle",
            "toilet twinkie"
        ],
        "insertable" : [
            "a 15\" spiked vibrator",
            "a 10 inch purple battery-operated monster",
            "a 9-iron",
            "a barbie doll",
            "a gerbil",
            "a lightbulb",
            "a number of chillies",
            "a squash",
            "an egg timer",
            "an antique doorknob",
            "my fist"
        ],
        "labia" : [
            "beef curtains",
            "clap flaps",
            "fishy flaps",
            "flappy meal",
            "furburger",
            "hairy goblet",
            "lunchmeat",
            "meaty hangers",
            "open-faced ham sandwich",
            "panty hamster",
            "piss flaps",
            "purple cabbage",
            "roast beef platter",
            "spam castanets",
            "velcro triangle",
            "vertical garden",
            "vertical smile"
        ],
        "lady_cum" : [
            "beige slime",
            "clunge gunge",
            "fallopian fish stock",
            "flange custard",
            "minge monsoon",
            "minge mucus",
            "pussy batter",
            "sex wee",
            "shrimp sap",
            "spaff",
            "tuna tunnel tears",
            "vertical moisture"
        ],
        "masturbate" : [
            "audition the finger puppets",
            "buff the muff",
            "dial the rotary phone",
            "finger blast",
            "fish for pearls",
            "flick the bean",
            "fluff the muff",
            "get a stinky pinky",
            "play the clitar",
            "study english cliterature",
            "strum the banjo",
            "stimulate the genitals through phalangetic motion",
            "tune the tuna"
        ],
        "menstruation" : [
            "been on the rag",
            "been riding the cotton pony",
            "been surfing the crimson tide",
            "been up on bricks",
            "been walking the red carpet",
            "had Aunt Flo visiting",
            "had my redwings",
            "had the painters in"
        ],
        "mouth" : [
            "cake hole",
            "laryngina",
            "mouth",
            "throat"
        ],
        "penis" : [
            "all-beef thermometer",
            "ample cock",
            "bald avenger",
            "balony pony",
            "bald-headed yogurt slinger",
            "batter blaster",
            "battering ram",
            "blind butler",
            "blood-engorged mayonnaise cannon",
            "blue-veined custard chucker",
            "brie baton",
            "bugger king",
            "clunger",
            "cunt stretcher",
            "cervix cigar",
            "cumtree",
            "chorizo howitzer",
            "chubstep",
            "cream reaper",
            "cunt plunger",
            "cheese-crusted cock",
            "disco stick",
            "devil's bagpipe",
            "eight inches of throbbing pink jesus",
            "flesh gordon",
            "greasy kebab skewer",
            "greasy slimelight",
            "gristle missile",
            "giggle stick",
            "huge penis",
            "jebend",
            "kebeb skewer",
            "long-dong silver",
            "love lollipop",
            "love muscle",
            "master of ceremonies",
            "meaty member",
            "muffbuster",
            "mutton dagger",
            "Nelson's Column",
            "Ocean's 11 Inches",
            "one-eyed milkman",
            "one-eyed monster",
            "pink tractor beam",
            "piss pipe",
            "purple beaver buster",
            "purple-headed trouser snake",
            "ramrod",
            "skeleton king",
            "skin flute",
            "slut slayer",
            "spam dagger",
            "spam javelin",
            "stilton sword",
            "sperminator",
            "spunk-filled spam rocket",
            "stilton spear",
            "tallywacker",
            "tenderloin truncheon",
            "thrill drill",
            "throbbing quim dagger",
            "timed slimer",
            "turgid terror truncheon",
            "vein cane",
            "veiny quim prod",
            "womb raider",
            "womb ferret",
            "washington monument",
            "wensleydale wand",
            "wrist-thick wand"
        ],
        "seepage" : [
            "porthole pudding",
            "rectal stew",
            "rectoplasm",
            "sphincter sauce"
        ],
        "semen" : [
            "baby gravy",
            "cock custard",
            "cock snot",
            "creamy load",
            "Da Vinci load",
            "ectoplasm",
            "gentleman's relish",
            "love mayonnaise",
            "love piss",
            "magician's wax",
            "man fat",
            "penis pudding",
            "steamin' semen"
        ],
        "testes" : [
            "chin pounders",
            "clock weights",
            "family jewels",
            "hairy walnuts",
            "jingle-jangle jewellery",
            "kids on a swing",
            "love spuds",
            "man berries",
            "man marbles",
            "salty protein grapes",
            "scroto baggins",
            "sperm factories",
            "trouser conkors",
            "two amigos",
            "wrecking balls"
        ],
        "vagina" : [
            "bearded haddock pasty",
            "birth cannon",
            "calamari cockring",
            "carp cavity",
            "chamber of squelch",
            "chlamydia canal",
            "clam-flavoured pothole",
            "clearing in the woods",
            "clunge pool",
            "cock holster",
            "cod canyon",
            "cod cave",
            "cod crater",
            "cum dumpster",
            "depravity cavity",
            "enchilada of love",
            "frilling pink golf bag",
            "front bum",
            "fuck gutter",
            "fuck trench",
            "furry cup",
            "gammon alley",
            "gaping clam cavern",
            "gashtray",
            "ground zero grotto",
            "hatchet wound",
            "herring hole",
            "hot pocket",
            "kipper dinghy",
            "ladytown",
            "meat purse",
            "moose knuckle",
            "mound of love pudding",
            "municipal cockwash",
            "one slice toaster",
            "oyster ditch",
            "penis pothole",
            "pink velvet sausage wallet",
            "quim",
            "Quimcy, M.E.",
            "salmon slit",
            "slime hole",
            "soft-shelled tuna taco",
            "shamevelope",
            "shame portal",
            "smush mitten",
            "south mouth",
            "sperm socket",
            "split peach",
            "spunk dungeon",
            "stench trench",
            "tampon tunnel",
            "tuna canal",
            "vaginal bacon buffet",
            "vibration station",
            "vibrator crater",
            "whispering eye",
            "wizards sleeve",
            "wunder down under"
        ]
    },
    "similes" : {
        "dribble" : [
            "a broken coffee maker",
            "a broken fridge freezer",
            "a George Foreman grill",
            "a hungry pig at a trough",
            "a jizz waterfall",
            "a leaky tap",
            "a rabid dog",
            "a slavering dog",
            "a slug in a salt mine",
            "Adele waiting for Greggs to open",
            "Augustus Gloop's mouth at the sight of Willy Wonka's chocolate river",
            "someone had poured fairy liquid into Niagara Falls",
            "there was a midget inside me with a super soaker",
            "Wayne Rooney's dick in an OAP home"
        ],
        "dry" : [
            "a nun's cunt",
            "Ghandi's flip flops"
        ],
        "eat" : [
            "a bulldog eating porridge",
            "a hungry hungry hippo",
            "a pig at a trough"
        ],
        "fast" : [
            "a greased weasel shit",
            "greased shit off a shiny shovel",
            "snot off a whip"
        ],
        "promiscuous" : [
            "been shot over more times than Sarajevo",
            "been told the sperm bank will accept my spit",
            "had more hands up me than The Muppets",
            "seen more action than Helmand Province",
            "seen more foreskins than a rabbi during a baby boom",
            "seen more helmets than Hitler",
            "seen more japseyes than an oriental optician",
            "seen more pricks than a second hand dartboard",
            "taken more poundings than the Somme"
        ],
        "shake" : [
            "a rat on acid",
            "a shitting dog",
            "a tasered slab of chopped liver",
            "an epileptic at a Pink Floyd concert",
            "jelly",
            "Micheal J. Fox licking a car battery",
            "Muhammad Ali on a tumble dryer",
            "Vanessa Feltz's diesel-powered vibrator"
        ],
        "sore" : [
            "a badly wrapped kebab",
            "a blind cobbler's thumb",
            "a bulldog licking piss from a thistle",
            "a bulldog in a windtunnel",
            "a bucket of smashed crabs",
            "a clown's pocket",
            "a darts team's goalkeeper",
            "a dropped burrito",
            "a gutted trout",
            "a hippo's yawn",
            "a horse's collar",
            "a manatee in yoga pants",
            "a motorway pileup",
            "a rabid baboon's arse",
            "a ripped out fireplace",
            "a sand blasted tomato",
            "a shot cat",
            "a stamped bat",
            "a stuntman's knee",
            "a twisted slipper",
            "a werewolf with it's throat cut",
            "an over inflated dinghy",
            "badly battered road kill",
            "Brian May's plughole",
            "John Wayne's saddlebags",
            "Pete Burns' lips",
            "Terry Waite's allotment",
            "that bathroom door in The Shining",
            "the Japanese flag",
            "the south end of a badger going north"
        ],
        "sweat" : [
            "a blind lesbian in a fish shop",
            "a dyslexic on Countdown",
            "a fat slag in a disco",
            "a gypsy near an unlocked shipping container",
            "a gypsy with a mortgage",
            "a midget nun at a penguin shoot",
            "a paedo during a prison riot",
            "a pregnant nun",
            "a white mouse in a tampon factory",
            "a whore in a confessional",
            "Gary glitter at PC World",
            "Joseph Fritzel on MTV Cribs",
            "Mike Tyson at a spelling bee"
        ],
        "tight" : [
            "a camel's arsehole in a sandstorm",
            "a mouse's ear",
            "a Scotsman"
        ],
        "wet" : [
            "a bathmaid's elbow",
            "a spastic's chin",
            "a well diggers arse",
            "an English summer",
            "an Italian cruise ship",
            "an otter's pocket"
        ]
    }
};
